'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073018_Database_copy_Amazon_RDS_Instance_Read_Replica_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073018_Database_copy_Amazon_RDS_Instance_Read_Replica-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073177_Compute__Networking_copy_Amazon_EMR_Cluster_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073177_Compute__Networking_copy_Amazon_EMR_Cluster-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073177_Non_Service_Specific_copy_Forums_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073177_Non-Service_Specific_copy_Forums-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073288_Compute__Networking_copy_Amazon_EC2_DB_on_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073288_Compute__Networking_copy_Amazon_EC2_DB_on_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073288_Non_Service_Specific_copy_Users_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073288_Non-Service_Specific_copy_Users-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073289_Database_copy_Amazon_RDS_MS_SQL_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073289_Database_copy_Amazon_RDS_MS_SQL_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073289_Deployment__Management_copy_AWS_Data_Pipeline_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073289_Deployment__Management_copy_AWS_Data_Pipeline-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073290_App_Services_copy_Amazon_Email_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073290_App_Services_copy_Amazon_Email-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073290_Database_copy_DynamoDB_Table_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073290_Database_copy_DynamoDB_Table-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_Compute__Networking_copy_Amazon_EMR_HDFS_Cluster_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_Compute__Networking_copy_Amazon_EMR_HDFS_Cluster-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_Database_copy_Amazon_RDS_MySQL_DB_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_Database_copy_Amazon_RDS_MySQL_DB_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_Database_copy_Amazon_RDS_Oracle_DB_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_Database_copy_Amazon_RDS_Oracle_DB_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_Database_copy_DynamoDB_Items_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_Database_copy_DynamoDB_Items-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_Non_Service_Specific_copy_Traditional_Server_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_Non-Service_Specific_copy_Traditional_Server-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073291_SDKs_copy_AWS_Toolkit_for_Visual_Studio_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073291_SDKs_copy_AWS_Toolkit_for_Visual_Studio-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073292_Database_copy_DynamoDB_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073292_Database_copy_DynamoDB-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073292_On_Demand_Workforce_copy_Amazon_Mechanical_Turk_Workers_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073292_On-Demand_Workforce_copy_Amazon_Mechanical_Turk_Workers-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073292_SDKs_copy_Android_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073292_SDKs_copy_Android-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073292_SDKs_copy_Tools_for_Windows_PowerShell_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073292_SDKs_copy_Tools_for_Windows_PowerShell-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Compute__Networking_copy_Amazon_EC2___256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Compute__Networking_copy_Amazon_EC2---256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Compute__Networking_copy_Amazon_VPC_VPN_Gateway_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Compute__Networking_copy_Amazon_VPC_VPN_Gateway-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Compute__Networking_copy_Auto_Scaling_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Compute__Networking_copy_Auto_Scaling-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Compute__Networking_copy_Elastic_Load_Balancing_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Compute__Networking_copy_Elastic_Load_Balancing-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Non_Service_Specific_copy_User_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Non-Service_Specific_copy_User-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_On_Demand_Workforce_copy_Amazon_Mechanical_Turk_Requester_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_On-Demand_Workforce_copy_Amazon_Mechanical_Turk_Requester-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073293_Storage__Content_Delivery_Amazon_CloudFront_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073293_Storage__Content_Delivery_Amazon_CloudFront-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_App_Services_copy_Amazon_Elastic_Transcoder_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_App_Services_copy_Amazon_Elastic_Transcoder-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_Compute__Networking_copy_Amazon_Route_53_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_Compute__Networking_copy_Amazon_Route_53-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_Compute__Networking_copy_Amazon_Route_53_Hosted_Zone_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_Compute__Networking_copy_Amazon_Route_53_Hosted_Zone-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_Compute__Networking_copy_Amazon_VPC_Internet_Gateway_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_Compute__Networking_copy_Amazon_VPC_Internet_Gateway-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_Deployment__Management_copy_AWS_CloudFormation_Template_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_Deployment__Management_copy_AWS_CloudFormation_Template-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_SDKs_copy_PHP_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_SDKs_copy_PHP-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073294_Storage__Content_Delivery_Amazon_Glacier_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073294_Storage__Content_Delivery_Amazon_Glacier-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_App_Services_copy_Amazon_SWF_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_App_Services_copy_Amazon_SWF-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_Deployment__Management_copy_IAM_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_Deployment__Management_copy_IAM-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_Deployment__Management_copy_OpsWorks_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_Deployment__Management_copy_OpsWorks-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_Non_Service_Specific_copy_Mobile_Client_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_Non-Service_Specific_copy_Mobile_Client-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_SDKs_copy_AWS_Toolkit_for_Eclipse_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_SDKs_copy_AWS_Toolkit_for_Eclipse-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073295_SDKs_copy_Java_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073295_SDKs_copy_Java-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_App_Services_copy_Amazon_CloudSearch_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_App_Services_copy_Amazon_CloudSearch-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_App_Services_copy_Amazon_SQS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_App_Services_copy_Amazon_SQS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_Compute__Networking_copy_Amazon_EC2_Instances_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_Compute__Networking_copy_Amazon_EC2_Instances-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_Compute__Networking_copy_Amazon_EMR___256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_Compute__Networking_copy_Amazon_EMR---256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_Compute__Networking_copy_Amazon_EMR_Cluster_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_Compute__Networking_copy_Amazon_EMR_Cluster-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_Database_copy_Amazon_ElasticCache_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_Database_copy_Amazon_ElasticCache-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073296_Database_copy_DynamoDB_Item_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073296_Database_copy_DynamoDB_Item-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Compute__Networking_copy_Amazon_VPC_Router_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Compute__Networking_copy_Amazon_VPC_Router-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Compute__Networking_copy_Amazon_VPC_VPN_Connection_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Compute__Networking_copy_Amazon_VPC_VPN_Connection-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Compute__Networking_copy_AWS_Direct_Connect_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Compute__Networking_copy_AWS_Direct_Connect-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Database_copy_DynamoDB_Attribute_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Database_copy_DynamoDB_Attribute-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Non_Service_Specific_copy_Forums_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Non-Service_Specific_copy_Forums-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073297_Storage__Content_Delivery_AWS_Storage_Gateway_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073297_Storage__Content_Delivery_AWS_Storage_Gateway-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_App_Services_copy_Amazon_SNS_Email_Notification_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_App_Services_copy_Amazon_SNS_Email_Notification-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Compute__Networking_copy_Amazon_EC2_AMI_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Compute__Networking_copy_Amazon_EC2_AMI-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Database_copy_Amazon_SimpleDB_Domain_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Database_copy_Amazon_SimpleDB_Domain-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Deployment__Management_copy_CloudWatch_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Deployment__Management_copy_CloudWatch-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Deployment__Management_copy_Elastic_Beanstalk_Deployment_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Deployment__Management_copy_Elastic_Beanstalk_Deployment-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Non_Service_Specific_copy_Corporate_Data_Center_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Non-Service_Specific_copy_Corporate_Data_Center-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Non_Service_Specific_copy_Internet_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Non-Service_Specific_copy_Internet-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_On_Demand_Workforce_copy_Amazon_Mechanical_Turk_Human_Intelligence_Tasks_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_On-Demand_Workforce_copy_Amazon_Mechanical_Turk_Human_Intelligence_Tas"& _ 
                        "ks-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073298_Storage__Content_Delivery_Amazon_S3_Bucket_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073298_Storage__Content_Delivery_Amazon_S3_Bucket-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Compute__Networking_copy_Amazon_VPC_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Compute__Networking_copy_Amazon_VPC-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Database_copy_Amazon_ElasticCache_Node_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Database_copy_Amazon_ElasticCache_Node-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Deployment__Management_copy_AWS_CloudFormation_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Deployment__Management_copy_AWS_CloudFormation-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Deployment__Management_copy_CloudWatch_Alarm_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Deployment__Management_copy_CloudWatch_Alarm-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Non_Service_Specific_copy__AWS_Cloud_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Non-Service_Specific_copy__AWS_Cloud-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Non_Service_Specific_copy_AWS_Management_Console_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Non-Service_Specific_copy_AWS_Management_Console-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Non_Service_Specific_copy_Tape_Storage_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Non-Service_Specific_copy_Tape_Storage-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073299_Storage__Content_Delivery_Amazon_CloudFront_Download_Distribution_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073299_Storage__Content_Delivery_Amazon_CloudFront_Download_Distribution-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_App_Services_copy_Amazon_SNS_Topic_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_App_Services_copy_Amazon_SNS_Topic-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_Compute__Networking_copy_Amazon_EC2_Elastic_IP_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_Compute__Networking_copy_Amazon_EC2_Elastic_IP-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_Compute__Networking_copy_Elastic_Network_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_Compute__Networking_copy_Elastic_Network_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_Database_copy_Amazon_RedShift_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_Database_copy_Amazon_RedShift-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_Database_copy_Amazon_SimpleDB_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_Database_copy_Amazon_SimpleDB-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_Non_Service_Specific_copy_Virtual_Private_CLoud__256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_Non-Service_Specific_copy_Virtual_Private_CLoud_-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_On_Demand_Workforce_copy_Amazon_Mechanical_Turk_assignment_task_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_On-Demand_Workforce_copy_Amazon_Mechanical_Turk_assignment_task-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073300_SDKs_copy_nodeJS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073300_SDKs_copy_nodeJS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_App_Services_copy_Amazon_CloudSearch_SDF_metadata_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_App_Services_copy_Amazon_CloudSearch_SDF_metadata-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_App_Services_copy_Amazon_SQS_Message_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_App_Services_copy_Amazon_SQS_Message-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_Deployment__Management_copy_IAM_Add_on_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_Deployment__Management_copy_IAM_Add-on-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_Non_Service_Specific_copy_Generic_Database_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_Non-Service_Specific_copy_Generic_Database-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_SDKs_copy_Ruby_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_SDKs_copy_Ruby-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_Storage__Content_Delivery_Amazon_S3_Bucket_with_Objects_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_Storage__Content_Delivery_Amazon_S3_Bucket_with_Objects-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073301_Storage__Content_Delivery_AWS_Import_Export_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073301_Storage__Content_Delivery_AWS_Import_Export-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073302_App_Services_copy_Amazon_SNS_HTTP_Notification_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073302_App_Services_copy_Amazon_SNS_HTTP_Notification-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073302_Compute__Networking_copy_Amazon_Route_53_Route_Table_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073302_Compute__Networking_copy_Amazon_Route_53_Route_Table-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073302_Non_Service_Specific_copy_Client_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073302_Non-Service_Specific_copy_Client-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073302_Non_Service_Specific_copy_Multimedia_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073302_Non-Service_Specific_copy_Multimedia-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073303_Storage__Content_Delivery_Amazon_Glacier_Vault_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073303_Storage__Content_Delivery_Amazon_Glacier_Vault-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_App_Services_copy_Amazon_SWF_Decider_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_App_Services_copy_Amazon_SWF_Decider-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_App_Services_copy_Amazon_SWF_Worker_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_App_Services_copy_Amazon_SWF_Worker-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_Database_copy_DynamoDB_Attributes_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_Database_copy_DynamoDB_Attributes-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_Deployment__Management_copy_IAM_STS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_Deployment__Management_copy_IAM_STS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_SDKs_copy_Net_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_SDKs_copy_Net-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073305_Storage__Content_Delivery_Amazon_S3_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073305_Storage__Content_Delivery_Amazon_S3-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_App_Services_copy_Amazon_SES_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_App_Services_copy_Amazon_SES-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_Compute__Networking_copy_Amazon_EC2_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_Compute__Networking_copy_Amazon_EC2_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_Database_copy_Amazon_RDS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_Database_copy_Amazon_RDS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_SDKs_copy_CLI_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_SDKs_copy_CLI-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_SDKs_copy_iOS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_SDKs_copy_iOS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073306_SDKs_copy_Python_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073306_SDKs_copy_Python-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073307_App_Services_copy_Amazon_SNS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073307_App_Services_copy_Amazon_SNS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073307_Compute__Networking_copy_Amazon_VPC_Customer_Gateway_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073307_Compute__Networking_copy_Amazon_VPC_Customer_Gateway-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073307_Deployment__Management_copy_Elastic_Beanstalk_Application_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073307_Deployment__Management_copy_Elastic_Beanstalk_Application-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073307_On_Demand_Workforce_copy_Amazon_Mechanical_Turk_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073307_On-Demand_Workforce_copy_Amazon_Mechanical_Turk-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073307_Storage__Content_Delivery_Amazon_CloudFront_Streaming_Distribution_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073307_Storage__Content_Delivery_Amazon_CloudFront_Streaming_Distribution-256"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_App_Services_copy_Amazon_SQS_Queue_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_App_Services_copy_Amazon_SQS_Queue-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Database_copy_Amazon_RDS_DB_Instance_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Database_copy_Amazon_RDS_DB_Instance-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Deployment__Management_copy_AWS_CloudFormation_Stack_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Deployment__Management_copy_AWS_CloudFormation_Stack-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Deployment__Management_copy_Elastic_Beanstalk_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Deployment__Management_copy_Elastic_Beanstalk-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Non_Service_Specific_copy_Disk_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Non-Service_Specific_copy_Disk-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Storage__Content_Delivery_Amazon_EBS_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Storage__Content_Delivery_Amazon_EBS-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Storage__Content_Delivery_Amazon_EBS_Volume_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Storage__Content_Delivery_Amazon_EBS_Volume-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073308_Storage__Content_Delivery_Amazon_S3_Objects_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073308_Storage__Content_Delivery_Amazon_S3_Objects-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Compute__Networking_copy_Amazon_EC2_CloudWatch_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Compute__Networking_copy_Amazon_EC2_CloudWatch-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Database_copy_Amazon_RDS_Instance_Read_Replica_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Database_copy_Amazon_RDS_Instance_Read_Replica-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Database_copy_Amazon_RDS_Instance_Standby_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Database_copy_Amazon_RDS_Instance_Standby-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Storage__Content_Delivery_Amazon_CloudFront_Edge_Location_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Storage__Content_Delivery_Amazon_CloudFront_Edge_Location-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Storage__Content_Delivery_Amazon_EBS_Snapshot_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Storage__Content_Delivery_Amazon_EBS_Snapshot-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1428073309_Storage__Content_Delivery_Amazon_Glacier_Archive_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1428073309_Storage__Content_Delivery_Amazon_Glacier_Archive-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
